#
#  __  __            _         _         _                  _
# |  \/  | __ _ _ __| | ____ _| |_ __ _ | |_ ___  _ __ ___ | |
# | |\/| |/ _` | '__| |/ / _` | __/ _` || __/ _ \| '_ ` _ \| |
# | |  | | (_| | |  |   < (_| | || (_| || || (_) | | | | | | |
# |_|  |_|\__,_|_|  |_|\_\__,_|\__\__,_(_)__\___/|_| |_| |_|_|
#
#                                                         todo
 
[markata]
# bump site version to bust GitHub actions cache
site_version = 1
 
# 2 weeks in seconds
default_cache_expire = 1209600
 
## Markata Setup
glob_patterns = "tasks/**/*.md"
hooks = [
    "markata_todoui",
    "default",
   ]
disabled_hooks = [
]
 
## Site Config
url = "https://todo.example.com"
title = "My Todos"
description = "Tracking my todo items with an awesome TUI"
rss_description = "todoui"
author_name = "Your Name"
author_email = "email@example.com"
# icon = "favicon.ico"
lang = "en"
# post_template = "pages/templates/post_template.html"
# amp_template = "pages/templates/post_template.amp.html"
theme_color = "#322D39"
background_color = "#B73CF6"
start_url = "/"
site_name = "Markata"
short_name = "aa"
display = "minimal-ui"
twitter_card = "summary_large_image"
twitter_creator = "@handle"
twitter_site = "@handle"
 
[markata.feeds.all]
title="all items"
filter="True"
card_template="<li class='post'><a href='/{{ slug }}/'>{{ slug }}</a></li>"
 
[markata.feeds.todo]
title="todo list"
filter="status=='done'"
card_template="<li class='post'><a href='/{{ slug }}/'>{{ slug }}</a></li>"
 
[markata.feeds.doing]
title="doing list"
filter="status=='doing'"
card_template="<li class='post'><a href='/{{ slug }}/'>{{ slug }}</a></li>"
 
[markata.todoui]
# set editor to open file in nvim inside a new terminal
editor='kitty nvim {file}'
# set new post to call copier template in a tmux popup
new_post='tmux popup -d "~/git/markata-todoui-sample" copier copy ~/.copier-templates/todo ~/git/markata-todoui-sample/'

[markata.todoui.keys]
q="quit"
l="next_stack"
L="move_next"
H="move_previous"
J="lower_priority"
K="raise_priority"
h="prev_stack"
r="refresh"
j="next_post"
k="prev_post"
enter="open_post"
n="new_post"
"ctrl+@"="show_config"
c="show_config"
g="first_post"
G="last_post"
D="delete_post"

